<?php if (!defined('IN_TANDEM')) die(); ?>
<!DOCTYPE html>
<html>

<head>
  <meta charset="utf-8">
  <title><?php __('SITE_NAME'); ?></title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/picnic">
  <link rel="stylesheet" href="css/style.css?<?php CacheBuster('css/style.css'); ?>">
</head>

<body>
  <main>
    <article class="card">
      <header>
        <?php __('LEGAL_TITLE'); ?>
      </header>
      <section class="content scroll-shadows">
        <?php __('LEGAL_CONTENT'); ?>
      </section>
      <footer>
        <a href="/" class="button"><?php __('BUTTON_HOME'); ?></a>
      </footer>
    </article>
    <footer>
      <p><?php __('ABOUT_TEXT_1'); ?> <a target="_blank" href="https://github.com/shuuryou">shuuryou</a> <?php __('ABOUT_TEXT_2'); ?></p>
    </footer>
  </main>
</body>

</html>