<?php
if (!defined('IN_TANDEM')) die();

global $HTML_LOCALIZE;
$HTML_LOCALIZE =
[
    'SITE_NAME' => 'Tandem Collabo',
    'STEP0_TITLE' => 'Welcome to Tandem Collabo',
    'STEP0_INTRO_TEXT' => 'Welcome to Tandem Collabo, a free platform designed to enhance language exchanges. Offer visual text corrections and add personalized notes to give detailed feedback to your conversation partner.',
    'STEP0_INTRO_TEXT2' => 'Getting started is simple:',
    'STEP0_INTRO_STEP1' => 'Paste the original message from your conversation partner without any changes.',
    'STEP0_INTRO_STEP2' => 'Apply your corrections to the text.',
    'STEP0_INTRO_STEP3' => 'Review your corrections and add notes to further explain your changes.',
    'STEP0_INTRO_STEP4' => 'Get a private link to your annotated corrections and share it with your conversation partner.',
    'STEP0_CALL_TO_ACTION' => 'To begin, just click "Begin" below.',
    'STEP1_TITLE' => 'Paste Original Message',
    'STEP1_INTRO_TEXT' => 'Paste the original message from your conversation partner here without any modifications. You’ll have the opportunity to correct it in the next step.',
    'STEP1_CONTENT_PLACEHOLDER' => 'Paste the original message here.',
    'STEP2_TITLE' => 'Correct the Text',
    'STEP2_INTRO_TEXT' => 'Now, make your corrections to the text below. You will be able to annotate your corrections with notes in the following step.',
    'STEP3_TITLE' => 'Review & Annotate',
    'STEP3_INTRO_TEXT' => 'Review how your corrections will appear to your conversation partner. Select text to add a note explaining your correction. Once you’re satisfied, click "Next".',
    'STEP4_TITLE' => 'Confirm You’re Not a Robot',
    'STEP4_INTRO_TEXT' => 'Please solve the challenge below to confirm you’re not a robot. Then, click "Next" to continue.',
    'STEP5_TITLE' => 'Share Your Corrections',
    'STEP5_INTRO_TEXT' => 'Use the link below to share your corrections and notes with your conversation partner.',
    'NOT_FOUND_TITLE' => 'Not Found',
    'NOT_FOUND_TEXT' => 'Sorry, this page does not exist.',
    'NOTE_MODAL_PLACEHOLDER' => 'Type your note here. Press "Add" when you’re done.',
    'BUTTON_OK' => 'OK',
    'BUTTON_PREVIOUS' => 'Previous',
    'BUTTON_NEXT' => 'Next',
    'BUTTON_CANCEL' => 'Cancel',
    'BUTTON_ADD_NOTE' => 'Add Note',
    'BUTTON_ADD' => 'Add',
    'BUTTON_YES' => 'Yes',
    'BUTTON_NO' => 'No',
    'BUTTON_BEGIN' => 'Begin',
    'BUTTON_CHANGES' => 'Changes',
    'BUTTON_ORIGINAL' => 'Original',
    'BUTTON_CORRECTED' => 'Corrected',
    'BUTTON_HOME' => 'Home',
    'BUTTON_LEGAL' => 'Privacy and Terms',
    'VIEW_CHANGES_TITLE' => 'Tandem Collabo',
    'VIEW_CHANGES_TEXT' => 'Below are corrections for you. Underlind text has notes. Click or tap text to view.',
    'VIEW_ORIGINAL_TITLE' => 'Tandem Collabo',
    'VIEW_ORIGINAL_TEXT' => 'Below is the original text without any changes or corrections.',
    'VIEW_CORRECTED_TITLE' => 'Tandem Collabo',
    'VIEW_CORRECTED_TEXT' => 'Below is the text as corrected by your conversation partner.',
    'VIEW_FOOTER_MAKE_YOUR_OWN' => 'Want to share your own text corrections?',
    'ABOUT_TEXT_1' => 'Tandem Collabo made by ',
    'ABOUT_TEXT_2' => 'in 2024',
    'LEGAL_TITLE' => 'Privacy and Usage Notices',
    'LEGAL_CONTENT' => '@default.legal.html',
];

global $JS_LOCALIZE;
$JS_LOCALIZE =
[
    'TEXT_MISSING_TITLE' => 'Text Missing',
    'TEXT_MISSING_CONTENT' => 'Please enter or paste the original message text from your conversation partner to begin correcting it.',
    'CORRECTION_IS_SAME_TITLE' => 'No Changes Detected',
    'CORRECTION_IS_SAME_TEXT' => 'The corrected text appears to be the same as the original. Please review and make any necessary changes.',
    'CAPTCHA_FAILED_TITLE' => 'Verification Unsuccessful',
    'CAPTCHA_FAILED_TEXT' => 'Complete the verification to confirm you’re not a robot.',
    'NOTES_DELETED_ON_BACK_TITLE' => 'Notes Will Be Deleted',
    'NOTES_DELETED_ON_BACK_TEXT' => 'Going back will delete your notes. Continue?',
    'PREVIEW_ERROR_TITLE' => 'Preview Unavailable',
    'PREVIEW_ERROR_TEXT' => 'We encountered a problem generating your preview. %?',
    'STORE_ERROR_TITLE' => 'Saving Failed',
    'STORE_ERROR_TEXT' => 'We were unable to save your corrections. %?',
    'EMPTY_NOTE_DELETE_TITLE' => 'Delete Empty Note?',
    'EMPTY_NOTE_DELETE_TEXT' => 'This note is empty. Would you like to delete it?',
    'FRIENDLY_RESPONSE_400' => 'There’s a problem with the request.',
    'FRIENDLY_RESPONSE_401' => 'You need to be authorized to perform this action.',
    'FRIENDLY_RESPONSE_403' => 'You don’t have permission to do this.',
    'FRIENDLY_RESPONSE_429' => 'You’ve made too many requests. Please wait before trying again.',
    'FRIENDLY_RESPONSE_500' => 'We’re experiencing internal issues. Please try again later.',
    'FRIENDLY_RESPONSE_UNKNOWN' => 'An unexpected error occurred. (%?) %?',
];